### ISSUE TITLE
mercury TX/RX TCP test

### ISSUE THREAD

**Issue by djbr1** [Rhizomatica/mercury#3]
I have created test setup on linux laptop where input/output are connected using 3.5 mm cable (kind of loopback plug)

Created separate binaries mercury_RX_TCP, mercury_RX_TEST, mercury_TX_TCP and mercury_TX_TEST by modifying telecom_system.operation_mode in main.cc

1) mercury_TX_TEST and mercury_RX_TEST  started separately work  => "noise" (transmission) can be heard and RX receives something

2) mercury_TX_TCP and mercury_RX_TCP are configured to listen on ports 6002 and 6003 respectively

scenario:
mercury_RX_TCP is started, netcat connected to port 6003 (nc   0 6002  > data2) 
mercury_RX_TEST is started and there are random bits received in data2 file 

Problem:
when mercury_TX_TCP is started, and some ASCII data sent to it using netcat (nc 0 50063) , mercury_TX_TCP responds with OK, there is "noise" from transmission however nothing received on mercury_RX_TCP

Please advise

**Comment by djbr1** [comment]
Hello,
 telecom_system.tcp_socket.timeout_ms increased to 60000 milisec, tcp client does not disconnect during test.
problem persists:
- RX TCP receives from TX TEST
- nothing received on RX TCP when sent from TX TCP although sound can be heard

**Comment by Fadijerji** [comment]
Please varify that the TCP message that you are sending to the Mercury_TCP_TX  has only 0's and 1's in byte format and not ASCII data, use Hexadecimal mode with only the two values: 0x00 and 0x01, the Mercury_TCP_TX is only configured at this stage to receive binary messages in bytes format.

Fadi

**Comment by djbr1** [comment]
Hi Fadi

Thanks for advice, now it works. 
Hint:  file has to be large enough, smaller file (4K) did not work. 
Question: why received file is like three times smaller than the one I sent ? 

[binary2.bin.gz](https://github.com/Rhizomatica/mercury/files/10323812/binary2.bin.gz)

**Comment by Fadijerji** [comment]
I am glad it is working now.

Regarding the file size, The current version of Mercury does not have a mechanism to divide a big file (bigger than the message length in bits) into data chunks yet.

Please note that the message size is 1600 bits, and depending on the LDPC code rate, part of the message is used for error correction.

If the code rate of 14/16 is used, then only (1400) bits are used for data and the rest  (200) for data protection (parity). Then due to framing the practical size is a little bit smaller (printed at the beginning as nBits)

So if you need to send more than (nBits-200) bits in the case, you will need to divide the file into chunks of exactly (nBits-200) (if less, the rest is filled with random data).

Fadi
